- name: Preinstall packages
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'software-properties-common', 'curl', 'gnupg2']
    update_cache: yes

- name: Add docker gpg key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Remove a Apt specific signing key, leading 0x is valid
  apt_key:
    id: 0EBFCD88
    state: present

- name:  Get docker repository
  shell: |
    echo "deb https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") $(lsb_release -cs) stable"
  register: debString


- name: Add docker repo in /etc/apt/sources.list
  lineinfile:
    path: /etc/apt/sources.list
    line: "{{debString.stdout}}"

- name: Update apt cache
  apt:
    update_cache: yes

- name: Installing docker
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']

- name: Remove containerd config.toml
  ansible.builtin.file:
    path: /etc/containerd/config.toml
    state: absent

- name: Enable and start docker
  systemd:
    name: docker
    state: started
    enabled: yes
    daemon_reload: yes