- name: Copy template
  become: yes
  template:
    src: kubeadm-init.yaml.j2
    dest: /etc/kubeadm-init.yaml

- name: Init kubeadm
  shell: |
          kubeadm init --config=/etc/kubeadm-init.yaml --ignore-preflight-errors=all --v=5

- name: Get join token
  become: yes
  shell: kubeadm token create --print-join-command --v=5
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  register: kubernetes_join_command

- name: Copy join command to local file.
  become: yes
  local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777

